In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv("play_tennis.csv")

In [8]:
df.drop(columns=['day'],inplace=True)

In [10]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [12]:
#Trainig
#Lookup Table (Dictionary)
#Testing

In [14]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [15]:
py=9/14
pn=5/14

In [16]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [17]:
#Outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [18]:
Pon=0
Prn=2/5
Psn=3/5
Poy=4/9
Pry=3/9
Psy=2/9

In [19]:
#Temp

pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [20]:
PCoolNo=1/5
PHotNo=2/5
PMildNo=2/5

PCoolYes=3/9
PHotYes=2/9
PMildYes=4/9

In [21]:
#Humidity

pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
PHighNo=4/5
PNormalNo=1/5

PHighYes=3/9
PNormalYes=6/9

In [23]:
#Wind

pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [24]:
PStrongNo=3/5
PWeakNo=2/5

PStrongYes=3/9
PWeakYes=6/9

In [28]:
# Outlook=Sunny,Temp=Hot,Humidity=High,Wind=Weak
# for YES
Pyes=py*Psy*PHotYes*PHighYes*PWeakYes
print(Pyes)

0.007054673721340388

In [29]:
# for NO
PNo=pn*Psn*PHotNo*PHighNo*PWeakNo
print(PNo)

0.02742857142857143

In [30]:
# hence NO play because (PNo>PYes)